### ISSUE TITLE
ERROR: Service 'server' depends on service 'redis' which is undefined.

### ISSUE THREAD

**Issue by Justproof** [PabloRosales/keyword-tool#8]
Hi, Pablo. Would you point me in the right direction for installing your app?

There is an error when running the docker command : docker-compose up -d
Am I missing something that I need to configure in the .env.dev file? 

I added all my api keys and have tried installing docker on both windows and OSX, but am getting the same error. Service 'server' depends on service 'redis' which is undefined.

**Comment by PabloRosales** [comment]
Hey, I forgot to remove `redis` from the `docker-compose.yml` file, did it here:

https://github.com/PabloRosales/keyword-tool/commit/970717b82038f76bc1270a1afd3bd0f3dc6ee35c

Update your file to remove those, or do a pull for the latest code.

Let me know if that helps.

**Comment by Justproof** [comment]
That helped. Thank you so much.
